<?php
/**
 * Created by PhpStorm.
 * User: lenovo
 * Date: 2019/1/19
 * Time: 14:20
 */

namespace app\admin\controller;

use think\Request;
class Notice extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 公告列表
     */
    public function index()
    {
        $data = Request::instance()->post();

        //状态
        $where = [];
        if(!empty($data['status'])){
            $where['status'] = $data['status'];
        }
        $nModel = new \app\admin\model\Notice;
        $list = $nModel->getNoticeList($where);
        // 获取分页显示
        $page = $list->render();
        $this->assign('list', $list);
        $this->assign('page', $page);

        return view('index');
    }


    /**
     * 添加或编辑
     */
    public function add()
    {
        $id = Request::instance()->param('id');
        if(!empty($id)){
            $nModel = new \app\admin\model\Notice;
            $info = $nModel->getNoticeInfo($id);
            if(empty($info)){
                $this->error('找不到对应的数据');
            }

            $this->assign('id', $id);
            $this->assign('info', $info);
        }
        return view('add');
    }


    /**
     * 保存公告
     */
    public function save()
    {
        $data = Request::instance()->param();
        //数据监测
        $validate = new \app\admin\validate\notice;
        if (!$validate->scene('saveNotice')->check($data))
        {
            $this->error($validate->getError());
        }

        $nModel = new \app\admin\model\Notice;
        if(!empty($data['id']))
        {
            //开始修改
            $res = $nModel->updateNoticeInfo($data);
            if($res === false){
                $this->error('修改失败，系统错误');
            }
        }else{
            //添加
            if(empty($data['sort'])){
                $maxSort = $nModel->getNoticeMaxs();
                $data['sort'] = $maxSort + 1;
            }
            $res = $nModel->addNoticeRes($data);
            if(empty($res)){
                $this->error('添加失败，系统错误');
            }
        }
        $this->redirect('/admin/notice/index','',1,'ok');
    }


    /**
     * 删除
     */
    public function del()
    {
        $id = Request::instance()->param('id');
        if(empty($id)){
            $this->error('非法的参数');
        }

        //开始删除
        $nModel = new \app\admin\model\Notice;
        $res = $nModel->delNoticeRes($id);
        if(empty($res)){
            $this->error('删除失败，系统错误');
        }

        $this->redirect('/admin/notice/index','',1,'ok');
    }
}