<?php
/**
 * Created by PhpStorm.
 * User: lenovo
 * Date: 2019/1/4
 * Time: 20:15
 */

namespace app\admin\controller;

use think\Request;
use think\Db;
use think\session;
class Pay extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * 充值列表
     */
    public function index()
    {
        //搜索参数
        $data = Request::instance()->param();
        $status = Request::instance()->param('status');

        $where = [];
        if(!empty($status)|| $status === '0'){
            $where['status'] = $status;
            $this->assign('status', $status);
        }

        $tModel = new \app\admin\model\PayCheck;
        $list = $tModel->getUserPayList($where);

        // 获取分页显示
        $page = $list->render();
        $this->assign('list', $list);
        $this->assign('page', $page);
        // 渲染模板输出
        return view('index');
    }

    /**
     * 审核充值操作
     */
    public function pass()
    {
        //搜索参数
        $data = Request::instance()->param();
        empty($data['id']) && $this->error('参数不存在');
        empty($data['userid']) && $this->error('用户参数不存在');
        empty($data['type']) && $this->error('请传递类型参数');
        if($data['type'] == 'pass' || $data['type'] = 'reject'){
            $data['type'] == 'pass' && $updata = ['status' => 1];
            $data['type'] == 'reject' && $updata = ['status' => -1];
        }else{
            $this->error('类型参数非法');
        }

        //开始修改状态
        Db::startTrans();
        $payModel = new \app\admin\model\PayCheck;
        $uModel = new \app\admin\model\User;
        $fModel = new \app\admin\model\Finance;
        //先查看数据
        $pinfo = $payModel->lookUserCzInfo(['id' => $data['id'],'userid' => $data['userid']]);
        if(empty($pinfo)){
            $this->error('数据不存在');
        }

        //直接修改状态
        $result = $payModel->editUserCzStatus($data['id'], $data['userid'], $updata);
        //判断修改结果
        if(empty($result)) {
            Db::rollback();
            $this->error('该数据已被别人操作');
        }else{
            //开始给用户增加金额
            if($data['type'] == 'pass'){
                $userRes = $uModel->addUserMoneys($data['userid'], $pinfo['money']);
                if(empty($userRes)){
                    Db::rollback();
                    $this->error('增加用户金额失败，系统错误');
                }

                //成功，添加财务日志
                $str = ['uid' => $data['userid'], 'money' => $pinfo['money'],'name' => '充值','details' => "充值{$pinfo['money']}元",'types' => 1];
                $res = $fModel->addFinances($str);
                if(empty($res)){
                    Db::rollback();
                    $this->error('添加活动财务日志失败，系统错误');
                }
            }

            $mid = Session::get('admin_userid');
            $res = $payModel->editUserCzStatus($data['id'], $data['userid'], ['check_admin' => $mid, 'check_time' => date('Y-m-d H:i:s')]);
            if(empty($res)){
                Db::rollback();
                $this->error('修改失败，该数据已操作');
            }else{
                Db::commit();
                if($data['type'] == 'pass'){
                    $this->redirect('pay/index','',1,'OK');
                }else{
                    $this->success('驳回成功', '/admin/pay/index','',1);
                }

            }
        }
    }


    /**
     * 用户-提现审核
     */
    public function txIndex()
    {
        //搜索参数
        $data = Request::instance()->param();
        $where = [];
        if(!empty($data['status'])){
            $where['c.status'] = $data['status'];
            $this->assign('status', $data['status']);
        }

        $tModel = new \app\admin\model\Cash;
        $uModel = new \app\admin\model\User;
        $list = $tModel->getTxUserList($where,'c.*, u.money as user_money,u.frozen_money as user_frozen_money');

        // 获取分页显示
       $page = $list->render();
        $this->assign('list', $list);
        $this->assign('page', $page);
        // 渲染模板输出
        return View('txindex');
    }


    /**
     * 审核提现操作
     */
    public function txPass()
    {
        //搜索参数
        $data = Request::instance()->param();
        empty($data['id']) && $this->error('参数不存在');
        empty($data['userid']) && $this->error('用户参数不存在');
        empty($data['type']) && $this->error('请传递类型参数');
        if($data['type'] == 'pass' || $data['type'] = 'reject'){
            $data['type'] == 'pass' && $updata = ['status' => 1];
            $data['type'] == 'reject' && $updata = ['status' => -1];
        }else{
            $this->error('类型参数非法');
        }

        //开始修改状态
        Db::startTrans();
        $cModel = new \app\admin\model\Cash;
        $uModel = new \app\admin\model\User;
        //查看数据是否在
        $cinfo = $cModel->getTxInfoUser(['id' => $data['id'],'userid' => $data['userid']],'id,money');
        if(empty($cinfo)){
            $this->error('操作的数据不存在');
        }

        //直接修改状态
        $result = $cModel->editUserCzStatus($data['id'], $data['userid'], $updata);
        //判断修改结果
        if(empty($result)) {
            Db::rollback();
            $this->error('该数据已被别人操作');
        }else{
            //如果通过审核的话
            if($data['type'] == 'pass'){
                //比较冻结额和提现额
                $uinfo = $uModel->getDetails($data['userid'],'id,money,frozen_money');
                if($cinfo['money'] > $uinfo['frozen_money']){
                    Db::rollback();
                    $this->error('提现金额大于冻结金额，通过失败');
                }

                //减少用户冻结金额
                $reduceRes = $uModel->reduceUserMoneys($data['userid'], $cinfo['money']);
                if(empty($reduceRes)){
                    Db::rollback();
                    $this->error('减少用户冻结额失败，系统错误');
                }

                //成功，添加财务日志
                $fModel = new \app\admin\model\Finance;
                $str = ['uid' => $data['userid'], 'money' => $cinfo['money'],'name' => '提现','details' => '提现'.$cinfo['money'].'元','types' => 2];
                $res = $fModel->addFinances($str);
                if(empty($res)){
                    Db::rollback();
                    $this->error('添加活动财务日志失败，系统错误');
                }
            }elseif ($data['type'] == 'reject'){
                //驳回的话，冻结金额，返回到用户余额中
                //减少-用户冻结金额
                $reduceRes = $uModel->reduceUserMoneys($data['userid'], $cinfo['money']);
                if(empty($reduceRes)){
                    Db::rollback();
                    $this->error('减少用户冻结额失败，系统错误');
                }

                //增加-用户余额
                $reduceRes = $uModel->addUserMoneys($data['userid'], $cinfo['money']);
                if(empty($reduceRes)){
                    Db::rollback();
                    $this->error('增加用户余额失败，系统错误');
                }
            }

            $mid = Session::get('admin_userid');
            $res = $cModel->editUserCzStatus($data['id'], $data['userid'], ['audit_admin' => $mid, 'check_time' => date('Y-m-d H:i:s')]);
            if(empty($res)){
                Db::rollback();
                $this->error('修改失败，该数据已操作');
            }else{
                Db::commit();
                if($data['type'] == 'pass'){
                    $this->success('通过，请尽快转账！', '/admin/pay/txIndex','',5);
                }else{
                    $this->success('驳回成功', '/admin/pay/txIndex','',1);
                }

            }
        }
    }

    /**
     * @return VIP审核列表
     */
    public function vipIndex()
    {
        //搜索参数
        $data = Request::instance()->param();
        $status = Request::instance()->param('status');

        $where = [];
        if(!empty($status)|| $status === '0'){
            $where['status'] = $status;
            $this->assign('status', $status);
        }

        $pModel = new \app\admin\model\paiVip;
        $uModel = new \app\admin\model\User;
        $list = $pModel->getUserPayVipList($where);
        // 获取分页显示
        $page = $list->render();

        $list = $list->toArray();

        //echo '<pre>';
        //var_dump($val);return;
        foreach ($list['data'] as $key => $val){

            $uinfo = $uModel->getDetails($val['userid'], 'mobile');
            if(!empty($uinfo['mobile'])){
                $list['data'][$key]['mobile'] = $uinfo['mobile'];
            }

        }


        $this->assign('list', $list['data']);
        $this->assign('page', $page);
        // 渲染模板输出
        return View('vip_index');
    }


    /**
     * VIP-通过or驳回操作
     */
    public function passVip()
    {
        //搜索参数
        $data = Request::instance()->param();
        empty($data['id']) && $this->error('参数不存在');
        empty($data['userid']) && $this->error('用户参数不存在');
        empty($data['type']) && $this->error('请传递类型参数');
        if($data['type'] == 'pass' || $data['type'] = 'reject'){
            $data['type'] == 'pass' && $updata = ['status' => 1];
            $data['type'] == 'reject' && $udpata = ['status' => -1];
            $data['type'] == 'reject' && $userUpdate = ['is_vip' => 4];
        }else{
            $this->error('类型参数非法');
        }

        //开始修改状态
        Db::startTrans();
        $vModel = new \app\admin\model\paiVip;
        $uModel = new \app\admin\model\User;
        //查看数据是否在
        $cinfo = $vModel->getPayVipUserInfo(['id' => $data['id'],'userid' => $data['userid']]);
        if(empty($cinfo)){
            $this->error('操作的数据不存在');
        }

        $data['type'] == 'pass' && $userUpdate = ['is_vip' => $cinfo['vip_type']];

        //直接修改状态
        $result = $vModel->editUserPayVipStatus($data['id'], $data['userid'], $updata);
        //判断修改结果
        if(empty($result)) {
            Db::rollback();
            $this->error('该数据已被别人操作');
        }else{
            //修改用户表状态
            if($data['type'] == 'pass')
            {
                $userUpdate['vip_time'] = date("Y-m-d H:i:s",strtotime("+1 year"));//一年后到期

            }
            $res = $uModel->editUserStatus($data['userid'], $userUpdate);
            if(empty($res)){
                Db::rollback();
                $this->error('修改用户VIP到期时间失败，系统错误');
            }

            //记录审核人信息
            $mid = Session::get('admin_userid');
            $res = $vModel->editUserPayVipInfo($data['id'], $data['userid'], ['check_admin' => $mid, 'check_time' => date('Y-m-d H:i:s')]);
            if(empty($res)){
                Db::rollback();
                $this->error('记录操作人信息失败，系统错误');
            }else{
                //增加充值记录，财务日志
                if($data['type'] == 'pass'){
                    $pcData = [
                        'userid' => $cinfo['userid'],
                        'money' => $cinfo['money'],
                        'status' => 1,
                        'tran_number' => $cinfo['tran_number'],
                        'check_admin' => $mid
                    ];
                    $pcModel = new \app\admin\model\PayCheck;
                    $fModel = new \app\admin\model\Finance;
                    $pcRes = $pcModel->insertGetId($pcData);
                    if(empty($pcRes)){
                        Db::rollback();
                        $this->error('添加充值记录失败，系统错误','/admin/pay/vipindex');
                        return;
                    }


                    $finAdd = [
                        'uid' => $cinfo['userid'],
                        'money' => $cinfo['money'],
                        'name' => '开通VIP',
                        'details' => "恭喜您成为VIP",
                        'types' => '2'
                    ];
                    $res = $fModel->addFinances($finAdd);
                    if(empty($res)){
                        Db::rollback();
                        $this->error('添加财务日志失败，系统错误','/admin/pay/vipIndex');
                        return;
                    }

                    Db::commit();
                    $this->success('通过', '/admin/pay/vipIndex','',1);
                }else{
                    Db::commit();
                    $this->success('驳回成功', '/admin/pay/vipIndex','',1);
                }

            }
        }
    }


    /**
     * 编辑-商家VIP信息页
     */
    public function editShopVips()
    {
        //搜索参数
        $data = Request::instance()->param();
        empty($data['id']) && $this->error('参数不存在');

        $id = intval($data['id']);
        empty($id) && $this->error('参数类型错误');

        //查找
        $vModel = new \app\admin\model\paiVip;
        $info = $vModel->getPayVipUserInfo(['id' => $id]);
        empty($info) && $this->error('不存在的VIP数据');

        //状态
        if($info['status'] != 0){
            $this->error('已审核的信息不能修改');
        }

        $this->assign('info', $info);
        return View('vip_edit');
    }


    /**
     * 保存-VIP信息
     */
    public function vipSave()
    {
        //搜索参数
        $data = Request::instance()->param();
        empty($data['id']) && $this->error('参数不存在');
        empty($data['userid']) && $this->error('用户参数不存在');

        $id = intval($data['id']);
        empty($id) && $this->error('参数类型错误');

        //查找
        $vModel = new \app\admin\model\paiVip;
        $info = $vModel->getPayVipUserInfo(['id' => $id]);
        empty($info) && $this->error('不存在的VIP数据');

        //状态
        if($info['status'] != 0){
            $this->error('已审核的信息不能修改');
        }

        //开始修改
        $res = $vModel->editUserPayVipInfo($data['id'], $data['userid'], ['cause' => $data['cause']]);
        empty($res) && $this->error('修改失败，系统错误');

        $this->success('成功', '/admin/pay/vipIndex','',1);

    }
}