<?php
/**
 * Created by PhpStorm.
 * User: lenovo
 * Date: 2018/12/23
 * Time: 16:36
 */

namespace app\admin\controller;

use think\Request;
class User extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 用户信息列表
     */
    public function index()
    {
        //搜索参数
        $data = Request::instance()->post();

        $where = [];
        if(!empty($data['mobile'])){
            $where['mobile'] = $data['mobile'];
            $this->assign('mobile', $data['mobile']);
        }

        if(!empty($data['id'])){
            $where['id'] = $data['id'];
            $this->assign('id', $data['id']);
        }

        $uModel = new \app\admin\model\User;
        $field = 'id,mobile,user_nickname,user_type,money,frozen_money,taobao_status,alipay_status,status';
        $list = $uModel->getUserList($where,$field);
        // 获取分页显示
        $page = $list->render();
        $this->assign('list', $list);
        $this->assign('page', $page);
        // 渲染模板输出
        return view('index');
    }


    /**
     * 商家信息列表
     */
    public function shopUserIndex()
    {
        //搜索参数
        $data = Request::instance()->post();

        $where = [];
        if(!empty($data['mobile'])){
            $where['mobile'] = $data['mobile'];
            $this->assign('mobile', $data['mobile']);
        }

        if(!empty($data['id'])){
            $where['id'] = $data['id'];
            $this->assign('id', $data['id']);
        }

        $uModel = new \app\admin\model\User;
        $field = 'id,mobile,user_nickname,user_type,money,frozen_money,taobao_status,alipay_status,status';
        $list = $uModel->getShopsList($where,$field);
        // 获取分页显示
        $page = $list->render();
        $this->assign('list', $list);
        $this->assign('page', $page);
        // 渲染模板输出
        return view('shop_index');
    }

    /**
     * 用户详细信息
     */
    public function detail()
    {
        //接收用户Id
        $id = Request::instance()->param('id');
        if(empty($id)){
            $this->error('请传递用户参数');
        }

        //找出详细信息
        $uModel = new \app\admin\model\User;
        $info = $uModel->getDetails($id);
        if(empty($info)){
            $this->error('不存在的用户信息');
        }

        $this->assign('userinfo', $info);
        return view('detail');

    }


    /**
     * 封号或解封账号
     */
    public function editStatus()
    {
        //接收用户Id
        $id = Request::instance()->param('id');
        if(empty($id)){
            $this->error('请传递用户参数');
        }

        //找出详细信息
        $uModel = new \app\admin\model\User;
        $info = $uModel->getDetails($id, 'id,status');
        if(empty($info)){
            $this->error('不存在的用户信息');
        }

        //开始操作
        $save = [];
        if($info['status'] == 1){
            $save['status'] = 2;
        }else{
            $save['status'] = 1;
        }

        $res = $uModel->editUserStatus($id, $save);
        if(empty($res)){
            $this->error('修改失败，系统错误');
        }

        $this->redirect('admin/User/index', '', 1, 'ok');
    }
}